# Generated by Django 5.2.3 on 2025-07-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuser',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='refresh_token',
            field=models.TextField(),
        ),
    ]
