# Generated by Django 5.2.3 on 2025-07-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_playlist_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifyuser',
            name='token_expires_in',
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
