# Generated by Django 5.2.3 on 2025-07-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0004_remove_spotifyuser_token_expires_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='token_expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
